name: Build and Deploy Frontend to Docker

on:
  push:
    branches:
      - master  # Este workflow se ejecutar치 cuando haya un push a la rama master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Checkout del c칩digo
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Docker Buildx (para construir im치genes Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Loguearse en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}  # Usa el secret DOCKER_USERNAME
          password: ${{ secrets.DOCKER_PASSWORD }}  # Usa el secret DOCKER_PASSWORD
        
      # Paso 4: Construir la imagen Docker para el frontend
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/mysql-front-api:${{ github.sha }} .
        
      # Paso 5: Verificar las im치genes Docker generadas
      - name: List Docker images
        run: |
          docker images
        
      # Paso 6: Subir la imagen Docker a Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/mysql-front-api:${{ github.sha }}
